# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestorder',
            old_name='quantity',
            new_name='received_quantity',
        ),
        migrations.AddField(
            model_name='requestorder',
            name='action',
            field=models.CharField(choices=[('receive', 'receive'), ('return', 'return')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestorder',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
