# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180725_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestorder',
            old_name='price',
            new_name='requested_price',
        ),
        migrations.AddField(
            model_name='requestorder',
            name='received_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
