# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-07 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('1', 'Administrator'), ('2', 'Cashier'), ('3', 'Store Keeper')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=20)),
                ('salary', models.PositiveIntegerField()),
                ('joined_on', models.DateField()),
                ('level', models.PositiveIntegerField()),
            ],
        ),
    ]
